#!/bin/bash

function createLandRegistry() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/land-registry.ousl.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/land-registry.ousl.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:5054 --caname ca-land-registry --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-land-registry.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-land-registry.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-land-registry.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-land-registry.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy land-registry's CA cert to land-registry's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem" "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/msp/tlscacerts/ca.crt"

  # Copy land-registry's CA cert to land-registry's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem" "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/tlsca/tlsca.land-registry.ousl.com-cert.pem"

  # Copy land-registry's CA cert to land-registry's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/ca"
  cp "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem" "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/ca/ca.land-registry.ousl.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-land-registry --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-land-registry --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-land-registry --id.name lradmin --id.secret lradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:5054 --caname ca-land-registry -M "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/msp" --csr.hosts peer0.land-registry.ousl.com --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:5054 --caname ca-land-registry -M "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls" --enrollment.profile tls --csr.hosts peer0.land-registry.ousl.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/peers/peer0.land-registry.ousl.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:5054 --caname ca-land-registry -M "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/users/User1@land-registry.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/users/User1@land-registry.ousl.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://lradmin:lradminpw@localhost:5054 --caname ca-land-registry -M "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/users/Admin@land-registry.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/land-registry/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/land-registry.ousl.com/users/Admin@land-registry.ousl.com/msp/config.yaml"
}

function createRegistrarGeneral() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/registrar-general.ousl.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:6054 --caname ca-registrar-general --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-registrar-general.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-registrar-general.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-registrar-general.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-registrar-general.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy registrar-general's CA cert to registrar-general's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem" "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/msp/tlscacerts/ca.crt"

  # Copy registrar-general's CA cert to registrar-general's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem" "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/tlsca/tlsca.registrar-general.ousl.com-cert.pem"

  # Copy registrar-general's CA cert to registrar-general's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/ca"
  cp "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem" "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/ca/ca.registrar-general.ousl.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-registrar-general --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-registrar-general --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-registrar-general --id.name rgadmin --id.secret rgadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:6054 --caname ca-registrar-general -M "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/msp" --csr.hosts peer0.registrar-general.ousl.com --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:6054 --caname ca-registrar-general -M "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls" --enrollment.profile tls --csr.hosts peer0.registrar-general.ousl.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/peers/peer0.registrar-general.ousl.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:6054 --caname ca-registrar-general -M "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/users/User1@registrar-general.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/users/User1@registrar-general.ousl.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://rgadmin:rgadminpw@localhost:6054 --caname ca-registrar-general -M "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/users/Admin@registrar-general.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/registrar-general/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/registrar-general.ousl.com/users/Admin@registrar-general.ousl.com/msp/config.yaml"
}

function createNotary() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/notary.ousl.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/notary.ousl.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-notary --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-notary.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-notary.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-notary.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-notary.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/notary.ousl.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy notary's CA cert to notary's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/notary.ousl.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/notary/ca-cert.pem" "${PWD}/organizations/peerOrganizations/notary.ousl.com/msp/tlscacerts/ca.crt"

  # Copy notary's CA cert to notary's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/notary.ousl.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/notary/ca-cert.pem" "${PWD}/organizations/peerOrganizations/notary.ousl.com/tlsca/tlsca.notary.ousl.com-cert.pem"

  # Copy notary's CA cert to notary's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/notary.ousl.com/ca"
  cp "${PWD}/organizations/fabric-ca/notary/ca-cert.pem" "${PWD}/organizations/peerOrganizations/notary.ousl.com/ca/ca.notary.ousl.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-notary --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-notary --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-notary --id.name notaryadmin --id.secret notaryadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-notary -M "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/msp" --csr.hosts peer0.notary.ousl.com --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/notary.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-notary -M "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls" --enrollment.profile tls --csr.hosts peer0.notary.ousl.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/notary.ousl.com/peers/peer0.notary.ousl.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-notary -M "${PWD}/organizations/peerOrganizations/notary.ousl.com/users/User1@notary.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/notary.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/notary.ousl.com/users/User1@notary.ousl.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://notaryadmin:notaryadminpw@localhost:7054 --caname ca-notary -M "${PWD}/organizations/peerOrganizations/notary.ousl.com/users/Admin@notary.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/notary/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/notary.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/notary.ousl.com/users/Admin@notary.ousl.com/msp/config.yaml"
}

function createOther() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/other.ousl.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/other.ousl.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-other --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-other.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-other.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-other.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-other.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/other.ousl.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy other's CA cert to other's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/other.ousl.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/other/ca-cert.pem" "${PWD}/organizations/peerOrganizations/other.ousl.com/msp/tlscacerts/ca.crt"

  # Copy other's CA cert to other's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/other.ousl.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/other/ca-cert.pem" "${PWD}/organizations/peerOrganizations/other.ousl.com/tlsca/tlsca.other.ousl.com-cert.pem"

  # Copy other's CA cert to other's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/other.ousl.com/ca"
  cp "${PWD}/organizations/fabric-ca/other/ca-cert.pem" "${PWD}/organizations/peerOrganizations/other.ousl.com/ca/ca.other.ousl.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-other --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-other --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-other --id.name otheradmin --id.secret otheradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-other -M "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/msp" --csr.hosts peer0.other.ousl.com --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/other.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-other -M "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls" --enrollment.profile tls --csr.hosts peer0.other.ousl.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/other.ousl.com/peers/peer0.other.ousl.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-other -M "${PWD}/organizations/peerOrganizations/other.ousl.com/users/User1@other.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/other.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/other.ousl.com/users/User1@other.ousl.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://otheradmin:otheradminpw@localhost:8054 --caname ca-other -M "${PWD}/organizations/peerOrganizations/other.ousl.com/users/Admin@other.ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/other/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/other.ousl.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/other.ousl.com/users/Admin@other.ousl.com/msp/config.yaml"
}



function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/ousl.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/ousl.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/ousl.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/ousl.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/ousl.com/msp/tlscacerts/tlsca.ousl.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/ousl.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/ousl.com/tlsca/tlsca.ousl.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/msp" --csr.hosts orderer.ousl.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/ousl.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls" --enrollment.profile tls --csr.hosts orderer.ousl.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/ousl.com/orderers/orderer.ousl.com/msp/tlscacerts/tlsca.ousl.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/ousl.com/users/Admin@ousl.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/ousl.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/ousl.com/users/Admin@ousl.com/msp/config.yaml"
}
